version: '2'
services:
  server:
    build: .
    container_name: test
    image: xananax/php
    depends_on:
      - db_mysql
      - db_postgres
    ports:
      - 3000:80
    volumes:
      - ./container/composer:/composer
      - ./container/data:/data
      - ./container/log/apache:/var/log
      - ./container/www:/var/www
      - ./container/www/html:/var/www/html
  db_mysql:
    image: mariadb
    logging:
      driver: none
    container_name: db_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    volumes:
      - ./container/data/mysql:/var/lib/mysql
      - ./container/log/mysql:/var/log
  db_postgres:
    image: postgres
    container_name: db_postgres
    logging:
      driver: none
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      PGDATA: /data
    volumes:
      - ./container/data/pgsql:/data
      - ./container/log/pgsql:/var/log
