version: '2'
services:
  server:
    build: .
    command: /bin/bash
    container_name: test
    image: xananax/php
    links:
      - db_mysql
      - db_postgres
    ports:
      - 8080:80
    volumes:
      - "composer:/composer"
      - "data:/data"
      - "log_server:/var/log"
      - "data_server:/var/www"
  db_mysql:
    image: mariadb
    container_name: db_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
    volumes:
      - "data_mysql:/var/lib/mysql"
      - "log_mysql:/var/log"
  db_postgres:
    image: postgres
    container_name: db_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      PGDATA: /data
    volumes:
      - "data_pgsql:/data"
      - "log_pgsql:/var/log"
volumes:
  - composer:./container/composer
  - data:./container/data
  - data_mysql:./container/data/mysql
  - data_pgsql:./container/data/pgsql
  - log:./container/log
  - log_pgsql:./container/log/pgsql
  - log_mysql:./container/log/mysql
  - log_server:./container/log/apache
  - data_server:./container/www
